INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Buffalo Bills', 'BUF', 'Ralph Wilson Stadium', 'Doug Marrone', 'AFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Miami Dolphins', 'MIA', 'Sun Life Stadium', 'Joe Philbin', 'AFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('New England Patriots', 'NE', 'Gillette Stadium', 'Bill Belichick', 'AFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('New York Jets', 'NYJ', 'MetLife Stadium', 'Rex Ryan', 'AFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Baltimore Ravens', 'BAL', 'M&T Bank Stadium', 'John Harbaugh', 'AFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Cincinnati Bengals', 'CIN', 'Paul Brown Stadium', 'Marvin Lewis', 'AFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Cleveland Browns', 'CLE', 'FirstEnergy Stadium', 'Mike Pettine', 'AFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Pittsburgh Steelers', 'PIT', 'Heinz Field', 'Mike Tomlin', 'AFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Houston Texans', 'HOU', 'NRG Stadium', 'Bill OBrien', 'AFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Indianapolis Colts', 'IND', 'Lucas Oil Stadium', 'Chuck Pagano', 'AFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Jacksonville Jaguars', 'JAC', 'EverBank Field', 'Gus Bradley', 'AFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Tennessee Titans', 'TEN', 'LP Field', 'Ken Whisenhunt', 'AFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Denver Broncos', 'DEN', 'Sports Authority Field', 'John Fox', 'AFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Kansas City Chiefs', 'KC', 'Arrowhead Stadium', 'Andy Reid', 'AFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Oakland Raiders', 'OAK', 'O.co Coliseum', 'Tony Sparano', 'AFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('San Diego Chargers', 'SD', 'Qualcomm Stadium', 'Mike McCoy', 'AFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Dallas Cowboys', 'DAL', 'AT&T Stadium', 'Jason Garrett', 'NFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('New York Giants', 'NYG', 'MetLife Stadium', 'Tom Coughlin', 'NFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Philadelphia Eagles', 'PHI', 'Lincoln Financial Field', 'Chip Kelly', 'NFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Washington Redskins', 'WAS', 'FedExField', 'Jay Gruden', 'NFC', 'East', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Chicago Bears', 'CHI', 'Soldier Field', 'Marc Trestman', 'NFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Detroit Lions', 'DET', 'Ford Field', 'Jim Caldwell', 'NFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Green Bay Packers', 'GB', 'Lambeau Field', 'Mike McCarthy', 'NFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Minnesota Vikings', 'MIN', 'TCF Bank Stadium', 'Mike Zimmer', 'NFC', 'North', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Atlanta Falcons', 'ATL', 'Georgia Dome', 'Mike Smith', 'NFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Carolina Panthers', 'CAR', 'Bank of America Stadium', 'Ron Rivera', 'NFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('New Orleans Saints', 'NO', 'Mercedes-Benz Superdome', 'Sean Payton', 'NFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Tampa Bay Buccaneers', 'TB', 'Raymond James Stadium', 'Lovie Smith', 'NFC', 'South', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Arizona Cardinals', 'ARI', 'University of Phoenix Stadium', 'Bruce Arians', 'NFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('St. Louis Rams', 'STL', 'Edward Jones Dome', 'Jeff Fisher', 'NFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('San Francisco 49ers', 'SF', 'Levis Stadium', 'Jim Harbaugh', 'NFC', 'West', 'true');
INSERT INTO teams (name, nickname, stadium, head_coach, conference, division, active) VALUES ('Seattle Seahawks', 'SEA', 'CenturyLink Field', 'Pete Carroll', 'NFC', 'West', 'true');
